export const EXCHANGE_CREATE_REQUEST = 'EXCHANGE_CREATE_REQUEST';
export const EXCHANGE_CREATE_SUCCESS = 'EXCHANGE_CREATE_SUCCESS';
export const EXCHANGE_CREATE_FAIL = 'EXCHANGE_CREATE_FAIL';
export const EXCHANGE_CREATE_RESET = 'EXCHANGE_CREATE_RESET';

export const EXCHANGE_LIST_MY_REQUEST = 'EXCHANGE_LIST_MY_REQUEST';
export const EXCHANGE_LIST_MY_SUCCESS = 'EXCHANGE_LIST_MY_SUCCESS';
export const EXCHANGE_LIST_MY_FAIL = 'EXCHANGE_LIST_MY_FAIL';
export const EXCHANGE_LIST_MY_RESET = 'EXCHANGE_LIST_MY_RESET';

export const EXCHANGE_DETAILS_REQUEST = 'EXCHANGE_DETAILS_REQUEST';
export const EXCHANGE_DETAILS_SUCCESS = 'EXCHANGE_DETAILS_SUCCESS';
export const EXCHANGE_DETAILS_FAIL = 'EXCHANGE_DETAILS_FAIL';

export const EXCHANGE_UPDATE_STATUS_REQUEST = 'EXCHANGE_UPDATE_STATUS_REQUEST';
export const EXCHANGE_UPDATE_STATUS_SUCCESS = 'EXCHANGE_UPDATE_STATUS_SUCCESS';
export const EXCHANGE_UPDATE_STATUS_FAIL = 'EXCHANGE_UPDATE_STATUS_FAIL';
export const EXCHANGE_UPDATE_STATUS_RESET = 'EXCHANGE_UPDATE_STATUS_RESET';

export const EXCHANGE_ADD_MESSAGE_REQUEST = 'EXCHANGE_ADD_MESSAGE_REQUEST';
export const EXCHANGE_ADD_MESSAGE_SUCCESS = 'EXCHANGE_ADD_MESSAGE_SUCCESS';
export const EXCHANGE_ADD_MESSAGE_FAIL = 'EXCHANGE_ADD_MESSAGE_FAIL';
export const EXCHANGE_ADD_MESSAGE_RESET = 'EXCHANGE_ADD_MESSAGE_RESET';